version: "3.8"
services:
  frontend:
    image: frontend-sveltekit
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/usr/src/app/frontend/src
      - ./frontend/static:/usr/src/app/frontend/static
      - ./frontend/vite.config.ts:/usr/src/app/frontend/vite.config.ts
      - ./frontend/tsconfig.json:/usr/src/app/frontend/tsconfig.json
      - ./frontend/svelte.config.js:/usr/src/app/frontend/svelte.config.js
      - ./frontend/.eslint.cjs:/usr/src/app/frontend/.eslint.cjs
      - ./frontend/.eslintignore:/usr/src/app/frontend/.eslintignore
      - ./frontend/.prettierrc:/usr/src/app/frontend/.prettierrc
      - ./frontend/.prettierignore:/usr/src/app/frontend/.prettierignore
      - ./frontend/postcss.config.cjs:/usr/src/app/frontend/postcss.config.cjs
      - ./frontend/tailwind.config.js:/usr/src/app/frontend/tailwind.config.js
      - ./frontend/.svelte-kit:/usr/src/app/frontend/.svelte-kit
    command: npm run dev
    environment:
      - PORT=5173
      - HOST=0.0.0.0
  backend:
    image: backend-golang
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      TODO_ENV: dev
      PORT: 8080
    volumes:
      - ./backend:/usr/src/app/backend
