version: "3.8"
services:
  frontend:
    container_name: frontend-sveltekit
    image: frontend-sveltekit
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/usr/src/app/frontend/src
      - ./frontend/static:/usr/src/app/frontend/static
      - ./frontend/vite.config.ts:/usr/src/app/frontend/vite.config.ts
      - ./frontend/tsconfig.json:/usr/src/app/frontend/tsconfig.json
      - ./frontend/svelte.config.js:/usr/src/app/frontend/svelte.config.js
      - ./frontend/.eslint.cjs:/usr/src/app/frontend/.eslint.cjs
      - ./frontend/.eslintignore:/usr/src/app/frontend/.eslintignore
      - ./frontend/.prettierrc:/usr/src/app/frontend/.prettierrc
      - ./frontend/.prettierignore:/usr/src/app/frontend/.prettierignore
      - ./frontend/postcss.config.cjs:/usr/src/app/frontend/postcss.config.cjs
      - ./frontend/tailwind.config.js:/usr/src/app/frontend/tailwind.config.js
      - ./frontend/.svelte-kit:/usr/src/app/frontend/.svelte-kit
    command: npm run dev
    environment:
      - PORT=5173
      - HOST=0.0.0.0
  backend:
    container_name: backend-golang
    image: backend-golang
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      TODO_ENV: dev
      PORT: 8080
      TODO_DB_HOST: todo-db
      TODO_DB_PORT: 3306
      TODO_DB_USER: todo
      TODO_DB_PASSWORD: todo
      TODO_DB_DATABASE: todo
    volumes:
      - ./backend:/usr/src/app/backend
  todo-db:
    image: mysql:8.0.29
    platform: linux/amd64
    container_name: todo-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
      MYSQL_DATABASE: todo
    volumes:
      - $PWD/backend/todo-db-data:/var/lib/mysql
      - $PWD/backend/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    ports:
      - "33306:3306"
