version: "3.8"
services:
  frontend:
    image: frontend-sveltekit
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5173"
    volumes:
      - ./frontend/src:/usr/src/app/frontend/src
      - ./frontend/static:/usr/src/app/frontend/static
      - ./frontend/vite.config.ts:/usr/src/app/frontend/vite.config.ts
      - ./frontend/tsconfig.json:/usr/src/app/frontend/tsconfig.json
      - ./frontend/svelte.config.js:/usr/src/app/frontend/svelte.config.js
    command: npm run dev
    environment:
      - PORT=5173
      - HOST=0.0.0.0
